import { useEffect, useState } from "react";
import { LoadingState } from "../components/UiProviders";
import { getAnalytics } from "../services/api";

type AnalyticsData = { timezone: string; start_date: string; end_date: string; weight: { measurement_count: number; latest_kg: number | null; change_kg: number | null; min_kg: number | null; max_kg: number | null; average_kg: number | null; daily: { date: string; weight_kg: number }[] }; nutrition: { totals: { calories_kcal: number; protein_g: number; carbohydrates_g: number; fat_g: number }; nutrition_missing_item_count: number; daily: { date: string; calories_kcal: number; protein_g: number; carbohydrates_g: number; fat_g: number }[] }; exercise: { session_count: number; total_duration_minutes: number; distance_km: number; calories_burned_kcal: number; daily: { date: string; duration_minutes: number; distance_km: number; calories_burned_kcal: number }[]; activity_types: { activity_type: string; session_count: number }[] } };

export function AnalyticsPage() {
  const [period, setPeriod] = useState<"7d" | "30d">("7d"); const [data, setData] = useState<AnalyticsData | null>(null); const [error, setError] = useState(false);
  useEffect(() => { setData(null); setError(false); void getAnalytics(period).then((value) => setData(value as AnalyticsData)).catch(() => setError(true)); }, [period]);
  const activityTypes = data && Array.isArray(data.exercise.activity_types) ? data.exercise.activity_types : [];
  return <main className="page-shell"><header className="page-header"><div><p className="eyebrow">Descriptive history</p><h1>Analytics</h1><p className="intro">Review the information you entered. Missing days and values are never invented.</p></div><label className="filter-field">Period<select aria-label="Period" value={period} onChange={(event) => setPeriod(event.target.value as "7d" | "30d")}><option value="7d">7 days</option><option value="30d">30 days</option></select></label></header>
    {!data && !error && <LoadingState label="Loading analytics…" />}{error && <section className="alert alert-error" role="alert"><strong>Analytics could not be loaded.</strong><span>Try another period or return to your tracking pages.</span></section>}
    {data && <><p className="muted-note">{data.start_date} to {data.end_date} · {data.timezone}</p><section className="content-grid"><article className="card"><p className="eyebrow">Weight history</p><h2>Recorded measurements</h2>{data.weight.measurement_count ? <div className="analytics-summary"><strong>{data.weight.latest_kg} kg</strong><span>Latest recorded weight</span><p>Latest: {data.weight.latest_kg} kg</p><dl><div><dt>Measurements</dt><dd>{data.weight.measurement_count}</dd></div><div><dt>Change</dt><dd>{data.weight.change_kg ?? "Not available"}</dd></div><div><dt>Range</dt><dd>{data.weight.min_kg}–{data.weight.max_kg} kg</dd></div><div><dt>Average</dt><dd>{data.weight.average_kg} kg</dd></div></dl></div> : <p className="empty-state">No weight data in this period.</p>}<p className="muted-note">Only dates with a recorded measurement are shown.</p></article>
      <article className="card"><p className="eyebrow">Nutrition entered</p><h2>Meal totals</h2><div className="metric-grid"><span><strong>{data.nutrition.totals.calories_kcal}</strong> kcal</span><span><strong>{data.nutrition.totals.protein_g}g</strong> protein</span><span><strong>{data.nutrition.totals.carbohydrates_g}g</strong> carbs</span><span><strong>{data.nutrition.totals.fat_g}g</strong> fat</span></div><p className="muted-note">{data.nutrition.nutrition_missing_item_count ? `${data.nutrition.nutrition_missing_item_count} items have missing nutrition values. Not entered values are not estimated.` : "All tracked meal items include some nutrition information."}</p></article>
      <article className="card"><p className="eyebrow">Exercise</p><h2>Activity totals</h2><div className="metric-grid"><span><strong>{data.exercise.session_count}</strong> sessions</span><span><strong>{data.exercise.total_duration_minutes}</strong> min</span><span><strong>{data.exercise.distance_km}</strong> km</span><span><strong>{data.exercise.calories_burned_kcal}</strong> kcal entered</span></div>{activityTypes.length > 0 && <ul className="compact-list activity-list">{activityTypes.map((item) => <li key={item.activity_type}><strong>{item.activity_type.replace("_", " ")}</strong><span>{item.session_count} session(s)</span></li>)}</ul>}</article>
      <article className="card"><p className="eyebrow">Data notes</p><h2>How these summaries work</h2><p className="muted-note">Nutrition and exercise are direct sums of what you entered. Daily nutrition and exercise values may include zero days; weight data does not.</p></article></section></>}
  </main>;
}
