import { FormEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";

import { createReminder, deleteReminder, listReminders, updateReminder } from "../services/api";
import type { Reminder, ReminderInput, ReminderScheduleType, ReminderType } from "../types/reminder";
import { useConfirm, useToast } from "../components/UiProviders";

const weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const emptyDraft = (): ReminderInput => ({ reminder_type: "weight", title: "", reminder_time: "08:00", schedule_type: "daily", day_of_week: null, enabled: true, note: null });
const label = (value: string) => value.replace("_", " ").replace(/^./, (character) => character.toUpperCase());

export function RemindersPage() {
  const confirm = useConfirm(); const { success } = useToast();
  const [reminders, setReminders] = useState<Reminder[]>([]); const [draft, setDraft] = useState<ReminderInput>(emptyDraft); const [editingId, setEditingId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void listReminders().then((result) => setReminders(result.items)).catch(() => setError("Reminders could not be loaded.")).finally(() => setLoading(false)); }, []);
  function validate() { if (!draft.title.trim()) return "Enter a reminder title."; if (!draft.reminder_time) return "Choose a reminder time."; if (draft.schedule_type === "weekly" && draft.day_of_week === null) return "Choose a weekday for a weekly reminder."; return null; }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const invalid = validate(); if (invalid) { setError(invalid); return; } setSaving(true); setError(null); try { const payload = { ...draft, title: draft.title.trim(), note: draft.note?.trim() || null, day_of_week: draft.schedule_type === "daily" ? null : draft.day_of_week }; const saved = editingId ? await updateReminder(editingId, payload) : await createReminder(payload); setReminders((items) => [...items.filter((item) => item.id !== saved.id), saved].sort((a, b) => a.reminder_time.localeCompare(b.reminder_time))); setDraft(emptyDraft()); setEditingId(null); const feedback = editingId ? "Reminder updated." : "Reminder saved."; setMessage(feedback); success(feedback); } catch { setError("Reminder could not be saved. Check the values and try again."); } finally { setSaving(false); } }
  function edit(reminder: Reminder) { setEditingId(reminder.id); setDraft({ reminder_type: reminder.reminder_type, title: reminder.title, reminder_time: reminder.reminder_time.slice(0, 5), schedule_type: reminder.schedule_type, day_of_week: reminder.day_of_week, enabled: reminder.enabled, note: reminder.note }); setError(null); }
  async function toggle(reminder: Reminder) { try { const saved = await updateReminder(reminder.id, { enabled: !reminder.enabled }); setReminders((items) => items.map((item) => item.id === saved.id ? saved : item)); success(`Reminder ${saved.enabled ? "enabled" : "disabled"}.`); } catch { setError("Reminder could not be updated."); } }
  async function remove(id: string) { if (!await confirm({ title: "Delete reminder?", description: "This reminder will be removed permanently." })) return; try { await deleteReminder(id); setReminders((items) => items.filter((item) => item.id !== id)); setMessage("Reminder deleted."); success("Reminder deleted."); } catch { setError("Reminder could not be deleted."); } }
  return <main className="page-shell"><Link className="back-link" to="/">← Today</Link><p className="eyebrow">Personal Health Tracking</p><h1>Reminders</h1><p className="intro">Create simple in-app reminders. They appear when you open the app; no push, email, SMS, or background delivery is used.</p>
    <form className="profile-form" onSubmit={submit} noValidate><h2>{editingId ? "Edit reminder" : "Add reminder"}</h2><label>Reminder type<select aria-label="Reminder type" value={draft.reminder_type} onChange={(event) => setDraft((item) => ({ ...item, reminder_type: event.target.value as ReminderType }))}><option value="weight">Weight</option><option value="meal">Meal</option><option value="exercise">Exercise</option><option value="custom">Custom</option></select></label><label>Title<input aria-label="Title" value={draft.title} maxLength={120} onChange={(event) => setDraft((item) => ({ ...item, title: event.target.value }))} /></label><label>Time<input aria-label="Time" type="time" value={draft.reminder_time} onChange={(event) => setDraft((item) => ({ ...item, reminder_time: event.target.value }))} /></label><label>Schedule<select aria-label="Schedule" value={draft.schedule_type} onChange={(event) => setDraft((item) => ({ ...item, schedule_type: event.target.value as ReminderScheduleType, day_of_week: event.target.value === "daily" ? null : item.day_of_week }))}><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label>{draft.schedule_type === "weekly" && <label>Weekday<select aria-label="Weekday" value={draft.day_of_week ?? ""} onChange={(event) => setDraft((item) => ({ ...item, day_of_week: Number(event.target.value) }))}><option value="">Choose a weekday</option>{weekdays.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></label>}<label><input aria-label="Enabled" type="checkbox" checked={draft.enabled} onChange={(event) => setDraft((item) => ({ ...item, enabled: event.target.checked }))} /> Enabled</label><label>Note (optional)<textarea aria-label="Reminder note" value={draft.note ?? ""} onChange={(event) => setDraft((item) => ({ ...item, note: event.target.value }))} /></label>{error && <p role="alert">{error}</p>}{message && <p aria-live="polite">{message}</p>}<button disabled={saving} type="submit">{saving ? "Saving…" : editingId ? "Update reminder" : "Save reminder"}</button>{editingId && <button className="secondary-button" type="button" onClick={() => { setEditingId(null); setDraft(emptyDraft()); }}>Cancel edit</button>}</form>
    <section className="history-section"><h2>Your reminders</h2>{loading ? <p>Loading reminders…</p> : reminders.length === 0 ? <p>No reminders yet. Add one above.</p> : <ul className="record-list">{reminders.map((reminder) => <li key={reminder.id}><div><strong>{reminder.reminder_time.slice(0, 5)} · {reminder.title}</strong><span>{label(reminder.reminder_type)} · {label(reminder.schedule_type)}{reminder.day_of_week !== null ? ` · ${weekdays[reminder.day_of_week]}` : ""}</span>{reminder.note && <span>{reminder.note}</span>}</div><div className="record-actions"><button className="secondary-button" type="button" onClick={() => void toggle(reminder)}>{reminder.enabled ? "Disable" : "Enable"}</button><button className="secondary-button" type="button" onClick={() => edit(reminder)}>Edit</button><button className="danger-button" type="button" onClick={() => void remove(reminder.id)}>Delete</button></div></li>)}</ul>}</section></main>;
}
