import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { EmptyState, LoadingState } from "../components/UiProviders";
import { ApiStatus } from "../features/health/ApiStatus";
import { Dashboard, getDashboard } from "../services/api";

const formatDate = (date: string, timezone: string) => new Intl.DateTimeFormat(undefined, { weekday: "long", month: "long", day: "numeric", timeZone: timezone }).format(new Date(`${date}T12:00:00Z`));

export function TodayPage() {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [error, setError] = useState(false);
  useEffect(() => { void getDashboard().then(setDashboard).catch(() => setError(true)); }, []);
  const profileName = dashboard?.profile?.preferred_name;
  return <main className="page-shell today-page">
    <header className="page-header today-header"><div><p className="eyebrow">Personal health tracking</p><h1>{profileName ? `Hello, ${profileName}` : "Today"}</h1><p className="intro">{dashboard ? `${formatDate(dashboard.date, dashboard.timezone)} · ${dashboard.timezone}` : "A clear, descriptive view of what you tracked today."}</p></div><div className="quick-actions" aria-label="Quick actions"><Link className="button" to="/weight">Add weight</Link><Link className="button button-secondary" to="/meals">Add meal</Link><Link className="button button-secondary" to="/exercise">Add exercise</Link></div></header>
    {error && <section className="alert alert-error" role="alert"><strong>Dashboard could not be loaded.</strong><span>Your tracking pages are still available from navigation.</span></section>}
    {!dashboard && !error && <LoadingState label="Loading your dashboard…" />}
    {dashboard && <><section className="stat-grid" aria-label="Today at a glance"><article className="stat-card"><span className="stat-label">Latest weight</span><strong>{dashboard.latest_weight ? `${dashboard.latest_weight.weight_kg} kg` : "Not entered"}</strong><span>{dashboard.latest_weight ? new Date(dashboard.latest_weight.recorded_at).toLocaleDateString() : "No weight records yet."}</span></article><article className="stat-card"><span className="stat-label">Meals today</span><strong>{dashboard.meals.count}</strong><span>{dashboard.meals.count ? `${dashboard.meals.item_count} logged items` : "No meals today."}</span></article><article className="stat-card"><span className="stat-label">Exercise today</span><strong>{dashboard.exercise.duration_minutes} min</strong><span>{dashboard.exercise.count ? `${dashboard.exercise.count} sessions` : "No sessions logged"}</span></article><article className="stat-card"><span className="stat-label">Active goals</span><strong>{dashboard.active_goals.length}</strong><span>{dashboard.active_goals.length ? "Personal targets" : "No active goals"}</span></article></section>
      <section className="content-grid"><article className="card nutrition-card"><div className="section-heading"><div><p className="eyebrow">Nutrition entered</p><h2>Meal summary</h2></div><Link to="/meals">View meals</Link></div>{dashboard.meals.count ? <div className="metric-grid"><span><strong>{dashboard.meals.calories_kcal}</strong> kcal</span><span><strong>{dashboard.meals.protein_g}g</strong> protein</span><span><strong>{dashboard.meals.carbohydrates_g}g</strong> carbs</span><span><strong>{dashboard.meals.fat_g}g</strong> fat</span></div> : <EmptyState title="No meals recorded today." action={<Link className="button button-secondary" to="/meals">Add a meal</Link>} />}{dashboard.meals.nutrition_missing_item_count > 0 && <p className="muted-note">Nutrition was not entered for {dashboard.meals.nutrition_missing_item_count} item(s).</p>}</article>
      <article className="card"><div className="section-heading"><div><p className="eyebrow">Activity</p><h2>Exercise summary</h2></div><Link to="/exercise">View exercise</Link></div>{dashboard.exercise.count ? <div className="metric-grid"><span><strong>{dashboard.exercise.duration_minutes}</strong> min</span><span><strong>{dashboard.exercise.distance_km}</strong> km</span><span><strong>{dashboard.exercise.calories_burned_kcal}</strong> kcal entered</span></div> : <EmptyState title="No exercise sessions today." action={<Link className="button button-secondary" to="/exercise">Add exercise</Link>} />}</article>
      <article className="card"><div className="section-heading"><div><p className="eyebrow">Your schedule</p><h2>Today's reminders</h2></div><Link to="/reminders">Manage</Link></div>{dashboard.reminders.length ? <ul className="timeline-list">{dashboard.reminders.map((reminder) => <li key={reminder.id}><time>{reminder.reminder_time.slice(0, 5)}</time><p>{reminder.title}</p><span className={`badge badge-${reminder.status}`}>{reminder.status === "due" ? "Due" : "Upcoming"}</span></li>)}</ul> : <EmptyState title="No reminders scheduled for today." action={<Link className="button button-secondary" to="/reminders">Manage reminders</Link>} />}</article>
      <article className="card"><div className="section-heading"><div><p className="eyebrow">Goals</p><h2>Active targets</h2></div><Link to="/goals">Manage</Link></div>{dashboard.active_goals.length ? <ul className="compact-list">{dashboard.active_goals.map((goal) => <li key={goal.id}><strong>{goal.target_value_kg} kg</strong><span>{goal.target_date ? `Target date ${goal.target_date}` : "No target date"}</span></li>)}</ul> : <EmptyState title="No active goals." action={<Link className="button button-secondary" to="/goals">Set a goal</Link>} />}</article></section></>}
    <section className="service-status"><ApiStatus /></section><p className="disclaimer">This application is for personal tracking and is not a substitute for professional medical advice.</p>
  </main>;
}
